name: nuget

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Pack NuGet packages
      run: dotnet pack --no-restore -c Release

    - name: Publish to NuGet.org
      run: |
        dotnet nuget push ./src/App/nupkg/hashdir.*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}}
        dotnet nuget push ./src/HashUtil/nupkg/ultimateanu.HashDir.HashUtil.*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{secrets.NUGET_LIBS_API_KEY}}
