name: test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore --framework net8.0

      - name: Build
        run: dotnet build --no-restore --framework net8.0

      - name: Test
        run: dotnet test --no-build --framework net8.0 --verbosity normal
